project:
  type: website

output-dir: docs

website:
  title: "Introduction to R Workshop Series"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: workshops/R_Tutorial_1_2025.qmd
        text: "Lesson 1"
      - href: workshops/R_Tutorial_2_2025.qmd
        text: "Lesson 2"
      - href: workshops/R_Tutorial_3_2025.qmd
        text: "Lesson 3"
      - href: workshops/R_Tutorial_4_2025.qmd
        text: "Lesson 4"
      - href: workshops/R_Tutorial_5_2025.qmd
        text: "Lesson 5"
      - href: workshops/R_Tutorial_6_2025.qmd
        text: "Lesson 6"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual
