project:
  type: website

website:
  title: "Introduction to R Workshop Series"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: workshops/R_Tutorial_1_2025.qmd
        text: "Lesson 1: Fundamentals of R"
      - href: workshops/R_Tutorial_3_2025.qmd
        text: "Lesson 3: Manipulating and plotting data in R"
      - href: workshops/R_Tutorial_5_2025.qmd
        text: "Lesson 5: Statistical analyses in R"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

output-dir: docs

