---
title: "Introduction to R Workshop Series"
---

This website hosts the materials for a 6-part Introduction to R Workshop series. These tutorials were developed in May-June 2025 as a set of resources for training users in manipulating, visualizing, and analyzing environmental data.

You can read through the tutorials on the website, but we recommend copying the code to your local RStudio, running through the script, and completing the challenges without looking at the answers!

The original workshop materials, including data to run the code, are stored in individual repositories at the following links:

- [Lesson 1: Fundamentals of R](https://github.com/wwoelmer/BOPRC_1_R_Fundamentals)
- [Lesson 2: Introduction to BOPRC's Interal Databases and Packages](https://github.com/JamesBOPRC/BOPRC_R_Course_Lesson_2)
- [Lesson 3: Manipulating and plotting time series data in R: Part 1 (monthly data)](https://github.com/wwoelmer/BOPRC_R_Course_Lesson_3)
- [Lesson 4: Manipulating and plotting time series data in R: Part 2 (high-frequency data)](https://github.com/JamesBOPRC/BOPRC_R_Course_Lesson_4)
- [Lesson 5: Statistical analyses in R](https://github.com/wwoelmer/BOPRC_R_Course_Lesson_5)
- [Lesson 6: Trend analysis](https://github.com/JamesBOPRC/BOPRC_R_Course_Lesson_6)

Click [here](files/Introduction_to_R.pptx) for an introductory presentation before completing the tutorials. 

